/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Nas {
  community: Generated<string | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  nasname: string;
  ports: Generated<number | null>;
  secret: Generated<string>;
  server: Generated<string | null>;
  shortname: Generated<string | null>;
  type: Generated<string | null>;
}

export interface Nasreload {
  nasipaddress: string;
  reloadtime: Date;
}

export interface Radacct {
  acctauthentic: Generated<string | null>;
  acctinputoctets: Generated<number | null>;
  acctinterval: Generated<number | null>;
  acctoutputoctets: Generated<number | null>;
  acctsessionid: Generated<string>;
  acctsessiontime: Generated<number | null>;
  acctstarttime: Generated<Date | null>;
  acctstoptime: Generated<Date | null>;
  acctterminatecause: Generated<string>;
  acctuniqueid: Generated<string>;
  acctupdatetime: Generated<Date | null>;
  calledstationid: Generated<string>;
  callingstationid: Generated<string>;
  class: Generated<string | null>;
  connectinfo_start: Generated<string | null>;
  connectinfo_stop: Generated<string | null>;
  delegatedipv6prefix: Generated<string>;
  framedinterfaceid: Generated<string>;
  framedipaddress: Generated<string>;
  framedipv6address: Generated<string>;
  framedipv6prefix: Generated<string>;
  framedprotocol: Generated<string | null>;
  nasipaddress: Generated<string>;
  nasportid: Generated<string | null>;
  nasporttype: Generated<string | null>;
  radacctid: Generated<number>;
  realm: Generated<string | null>;
  servicetype: Generated<string | null>;
  username: Generated<string>;
}

export interface Radcheck {
  attribute: Generated<string>;
  id: Generated<number>;
  op: Generated<string>;
  username: Generated<string>;
  value: Generated<string>;
}

export interface Radgroupcheck {
  attribute: Generated<string>;
  groupname: Generated<string>;
  id: Generated<number>;
  op: Generated<string>;
  value: Generated<string>;
}

export interface Radgroupreply {
  attribute: Generated<string>;
  groupname: Generated<string>;
  id: Generated<number>;
  op: Generated<string>;
  value: Generated<string>;
}

export interface Radpostauth {
  authdate: Generated<Date>;
  class: Generated<string | null>;
  id: Generated<number>;
  pass: Generated<string>;
  reply: Generated<string>;
  username: Generated<string>;
}

export interface Radreply {
  attribute: Generated<string>;
  id: Generated<number>;
  op: Generated<string>;
  username: Generated<string>;
  value: Generated<string>;
}

export interface Radusergroup {
  groupname: Generated<string>;
  id: Generated<number>;
  priority: Generated<number>;
  username: Generated<string>;
}

export interface Registrations {
  auth_method: "form" | "thaid";
  consent_at: Date;
  consent_version: string;
  created_at: Generated<Date>;
  doc_last4: Generated<string | null>;
  doc_number_enc: Buffer;
  doc_number_hmac: Generated<Buffer | null>;
  doc_type: "other" | "passport" | "pink_card" | "thai_id";
  expires_at: Date;
  full_name: string;
  id: Generated<number>;
  ip: Generated<string | null>;
  mac: string;
  phone: Generated<string | null>;
  session_username: string;
}

export interface DB {
  nas: Nas;
  nasreload: Nasreload;
  radacct: Radacct;
  radcheck: Radcheck;
  radgroupcheck: Radgroupcheck;
  radgroupreply: Radgroupreply;
  radpostauth: Radpostauth;
  radreply: Radreply;
  radusergroup: Radusergroup;
  registrations: Registrations;
}
